always-run:
  script: echo 'this should always run'

on-pull-requests:
  script: echo 'this should run on pull requests'
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"

except-pull-requests:
  script: echo 'This should not run for pull requests, but runs in other cases.'
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
      when: never
    - when: on_success
  
test:
  stage: test
  script:
    - cucumber Features --format junit --out reports/cucumber.xml
  artifacts:
    when: always
    reports:
      junit: reports/cucumber.xml
    paths:
      - reports/
