image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - test

test:
  stage: test
  script:
    - dotnet restore
    - dotnet test StepikTesting.sln --logger:"junit;LogFilePath=testresult.xml"
  artifacts:
    when: always
    reports:
      junit: testresult.xml
    paths:
      - testresult.xml
